---
- name: Install Kubernetes components
  hosts: 172.31.51.42
  become: yes

  tasks:
- name: Install AWS CLI
  shell:
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    sudo yum -y install unzip
    unzip awscliv2.zip
    sudo ./aws/install

- name: Install KOPS
  shell: 
    curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
    chmod +x kops
    sudo mv kops /usr/local/bin/kops

- name: Install KUBECTL
  shell: 
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/kubectl
---